spring.application.name=mycollector

server.port=9898

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=
spring.data.redis.timeout=3000ms

logging.level.com.example.mycollector=INFO

server.servlet.session.cookie.path=/

# ===== KMS ???? ? ?? ?? =====
hsck.encrypt.master=/home/hsck/bin/sginstall
hsck.encrypt.random=/etc/pki/hsck/server.key
hsck.encrypt.dek=/etc/pki/hsck/config.key

# ===== DB ??? ?? =====
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:15432/hsckdb
db.username=hqc5H0zHUjAJFRKKFPuUUQ==
db.password=an7vR1daO6tG+QirajoCDQ==