spring.application.name=mycollector

server.port=9898

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=
spring.data.redis.timeout=3000ms

logging.level.com.example.mycollector=INFO

# ===== KMS ???? ? ?? ?? =====
hsck.encrypt.master=???_????_??_??_??
hsck.encrypt.random=???_???_??_??_??
hsck.encrypt.dek=???_DEK_??_??_??

# ===== DB ??? ?? =====
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:15432/hsckdb
db.username=???_jdbc.properties?_db.Username_?_???_??
db.password=???_jdbc.properties?_db.Password_?_???_??